sudo: required
language: go

go:
  - 1.15.x

env:
  - GO111MODULE=on

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin   #login to dockerhub
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com  #login to registry.heroku.com

script:
  - make review-code-and-test
  - make test-coverage-report
  - docker build -t brunodecastroo/digital-accounts:v1 .
  - docker tag brunodecastroo/digital-accounts:v1 registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push brunodecastroo/digital-accounts:v1;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: master

after_success:
  - heroku container:login
  - heroku container:release web --app $HEROKU_APP_NAME