language: go

go:
  - 1.15.x

env:
  - GO111MODULE=on

services:
  - docker

script:
  - make review-code-and-test
  - make test-coverage-report

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key: "5159627c-f611-48bf-905b-ccb1223201df"
  app: digital-accounts
    on: master