version: "3.4"

volumes:
  postgres-volume:

services:
  api:
    container_name: "digital-accounts"
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      PORT: 9090
      SWAGGER_HOST: locahost:9090
      MIGRATION_PATH: migrations

  postgres:
    container_name: "postgres"
    image: "postgres:alpine"
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
        - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: digital_accounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
