version: "3.4"

volumes:
  postgres-volume:

services:

  postgres:
    container_name: "postgres"
    image: "postgres:alpine"
    restart: on-failure
    ports:
      - 5439:5432
    volumes:
        - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: digital_accounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
