version: '3.4'

services:
  api:
    build:
      context: ../
      dockerfile: .
    ports:
      - 9090:9090
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: digital_accounts

  postgres:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: digital_accounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
